[2025-06-27T04:38:28.546+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T04:38:28.598+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [queued]>
[2025-06-27T04:38:28.605+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [queued]>
[2025-06-27T04:38:28.606+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-27T04:38:28.631+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Structure_Data_With_Spark> on 2025-06-26 00:08:00+00:00
[2025-06-27T04:38:28.637+0000] {standard_task_runner.py:64} INFO - Started process 342 to run task
[2025-06-27T04:38:28.641+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_processing_pipeline', 'Structure_Data_With_Spark', 'scheduled__2025-06-26T00:08:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmprlviqv52']
[2025-06-27T04:38:28.644+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask Structure_Data_With_Spark
[2025-06-27T04:38:28.786+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [running]> on host 3b2681f5d151
[2025-06-27T04:38:29.150+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_processing_pipeline' AIRFLOW_CTX_TASK_ID='Structure_Data_With_Spark' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T00:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-26T00:08:00+00:00'
[2025-06-27T04:38:29.151+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T04:38:29.192+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-06-27T04:38:29.193+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.jars=hdfs://namenode:9000/user/spark/jars/* --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation
[2025-06-27T04:38:29.269+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-06-27T04:38:29.270+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2025-06-27T04:38:29.272+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T04:38:29.299+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.jars=hdfs://namenode:9000/user/spark/jars/* --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 1.
[2025-06-27T04:38:29.302+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_processing_pipeline, task_id=Structure_Data_With_Spark, run_id=scheduled__2025-06-26T00:08:00+00:00, execution_date=20250626T000800, start_date=20250627T043828, end_date=20250627T043829
[2025-06-27T04:38:29.342+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task Structure_Data_With_Spark (Cannot execute: spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.jars=hdfs://namenode:9000/user/spark/jars/* --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 1.; 342)
[2025-06-27T04:38:29.374+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-27T04:38:29.410+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-27T06:56:00.454+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T06:56:00.532+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [queued]>
[2025-06-27T06:56:00.549+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [queued]>
[2025-06-27T06:56:00.550+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-27T06:56:00.580+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Structure_Data_With_Spark> on 2025-06-26 00:08:00+00:00
[2025-06-27T06:56:00.589+0000] {standard_task_runner.py:64} INFO - Started process 280 to run task
[2025-06-27T06:56:00.596+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_processing_pipeline', 'Structure_Data_With_Spark', 'scheduled__2025-06-26T00:08:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp6nr8o1ef']
[2025-06-27T06:56:00.603+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask Structure_Data_With_Spark
[2025-06-27T06:56:00.918+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-27T06:56:01.217+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark scheduled__2025-06-26T00:08:00+00:00 [running]> on host 6c334e887217
[2025-06-27T06:56:01.674+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_processing_pipeline' AIRFLOW_CTX_TASK_ID='Structure_Data_With_Spark' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T00:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-26T00:08:00+00:00'
[2025-06-27T06:56:01.677+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T06:56:01.774+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-06-27T06:56:01.776+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation
[2025-06-27T06:56:04.151+0000] {spark_submit.py:571} INFO - Using properties file: null
[2025-06-27T06:56:04.272+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-06-27T06:56:04.275+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2025-06-27T06:56:04.276+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2025-06-27T06:56:04.277+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2025-06-27T06:56:04.278+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2025-06-27T06:56:04.278+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2025-06-27T06:56:04.279+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2025-06-27T06:56:04.280+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2025-06-27T06:56:04.281+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2025-06-27T06:56:04.281+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2025-06-27T06:56:04.281+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-06-27T06:56:04.311+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T06:56:04.351+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 1.
[2025-06-27T06:56:04.356+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_processing_pipeline, task_id=Structure_Data_With_Spark, run_id=scheduled__2025-06-26T00:08:00+00:00, execution_date=20250626T000800, start_date=20250627T065600, end_date=20250627T065604
[2025-06-27T06:56:04.381+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task Structure_Data_With_Spark (Cannot execute: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 1.; 280)
[2025-06-27T06:56:04.424+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-27T06:56:04.485+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T06:56:04.507+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
